export const LOAD_TRAVELS =  "LOAD_TRAVELS";
export const LOAD_DRIVERS =  "LOAD_TRAVELS";
export const LOAD_COMPANY =  "LOAD_COMPANY";
export const TRAVEL_APROVED = "TRAVEL_APROVE";
export const TRAVEL_CREATION = "TRAVEL_APROVE";
export const TRAVEL_ORDER_NUMBER = "TRAVEL_ORDER_NUMBER";
export const USER_AUTHENTICATION = "USER_AUTHENTICATION";
export const DOWNLOAD_VOUCHER = "DOWNLOAD_VOUCHER";
export const LOAD_VOUCHERS = "LOAD_VOUCHERS";
export const CLEAN_ORDER_NUMBER ="CLEAN_ORDER_NUMBER"

