export const LOAD_TRAVELS =  "LOAD_TRAVELS";
export const TRAVEL_APROVED = "TRAVEL_APROVE";
export const TRAVEL_CREATION = "TRAVEL_APROVE";
export const TRAVEL_ORDER_NUMBER = "TRAVEL_ORDER_NUMBER";
export const USER_AUTHENTICATION = "USER_AUTHENTICATION";
export const DOWNLOAD_VOUCHER = "DOWNLOAD_VOUCHER";
export const LOAD_VOUCHERS = "LOAD_VOUCHERS";

